version: '3'

services:
    mysql:
        image: mysql:5.6
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS:-secret}
            MYSQL_DATABASE: ${DB_NAME:-wordpress}
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: ${DB_PASS:-secret}

    wordpress:
        image: wordpress:php7.4-apache
        depends_on:
            - mysql
        ports:
            - ${WEB_PORT:-80}:80
        volumes:
            - ./public:/var/www/html
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: ${DB_PASS:-secret}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=wordpress
            - PMA_PASSWORD=${DB_PASS:-secret}
        links:
            - mysql
        ports:
            - 4040:80
volumes:
    db_data: